### ISSUE TITLE
Source configuration stopped working?

### ISSUE THREAD

**Issue by strzibny** [jshmrtn/currency-conversion#23]
I am trying to write tests in my project and the following seemed not to have any effect:
```
config :myproject, MyProject.CurrencyExchange,
  source: CurrencyConversion.Source.Test
```
Can you confirm this does not work anymore? Or it's expected that it's set as:

```
config :myproject, CurrencyConversion,
  source: CurrencyConversion.Source.Test
```
?

CurrencyExchange is the exchange module:

```
defmodule MyProject.CurrencyExchange do
  use CurrencyConversion, otp_app: :myproject
  ...
```

**Comment by maennchen** [comment]
@strzibny you have to configure it as `config :[your_app_name], [YourCurrencyModule], source: [SourceModule]`.

Since you defined your module as `CurrencyExchange` and not `MyProject.CurrencyExchange your second code example is correct.

**Comment by strzibny** [comment]
@maennchen That was just copy & edit mistake. Neither variant seems to work for me. I always get the exchange rates from the default `source`.

**Comment by maennchen** [comment]
@strzibny Can you `IO.inspect` what is in `config` here: https://github.com/jshmrtn/currency-conversion/blob/master/lib/currency_conversion.ex#L117 ?

**Comment by strzibny** [comment]
It's
```
[
  base_currency: :USD,
  source_protocol: "https",
  source: CurrencyConversion.Source.Test,
  refresh_interval: :manual,
  seed: &MyProject.CurrencyExchange.seed/1
]
```
So the configuration seems correct.

**Comment by strzibny** [comment]
So the problem is in using `seed` which is preferred. I don't think this is right. Seed is for populating initial data, but not for updates.
```
# in update_worker.ex
defp refresh(opts, load_callback \\ &load_from_source/1) do
```
`load_callback` would be the seed function.

**Comment by maennchen** [comment]
@strzibny The `seed` is only called on `init`, not for manual / automatic refreshes: https://github.com/jshmrtn/currency-conversion/blob/master/lib/currency_conversion/update_worker.ex#L30

I'll do some testing on my own soon. But I honestly think that you're configuring something wrong since a lot of the tests depend on setting a different source: https://github.com/jshmrtn/currency-conversion/blob/master/test/currency_conversion_test.exs#L17

**Comment by strzibny** [comment]
@maennchen it's possible hence the question from the beggining. Actually now in `iex` console this is looking good. Let me find the culprit and don't waste your time for now. I would come back to close it.

**Comment by strzibny** [comment]
Ya, I made mistake in some tests and it was ordered dependent. Probably all is well. Sorry about the noise.
