### ISSUE TITLE
Getting the error - function CurrencyConversion.__using__/1 is undefined or private

### ISSUE THREAD

**Issue by GishaJamesY** [jshmrtn/currency-conversion#24]
when I define it with
```
defmodule MyApp.CurrencyConversion do
  use CurrencyConversion, otp_app: :my_app
end
```

I am getting the error - `function CurrencyConversion.__using__/1 is undefined or private`

**Comment by maennchen** [comment]
Is seems you installed a 0.x.x version and not the 1.0.0 branch.
