### ISSUE TITLE
Expected behaviour on invalid API key

### ISSUE THREAD

**Issue by nbernardes** [jshmrtn/currency-conversion#26]
When giving an invalid api key or an api key that has exceeded the authorized amount of requests (rate limit), the following error is returned and the application never starts.
''' elixir
[error] An error occured while rereshing currency rates. "Fixer API Schema has changed."
** (Mix) Could not start application currency_conversion: CurrencyConversion.Application.start(:normal, []) returned an error: shutdown: failed to start child: CurrencyConversion.UpdateWorker
    ** (EXIT) {:error, "Fixer API Schema has changed."}
'''

What is the recommended approach when this error happens?

**Comment by maennchen** [comment]
@nunobernardes99 I don't see a solution as long as the data can't be loaded other than ensuring that it can do so.

It would be possible to store the rates in an independent ETS table and only restart the update worker. If it fails repeatedly, I crash is still the right way to go in my opinion.

I therefore think, that only the error should be changed. `Fixer API Schema has changed.` => `Rate Limit reached` or `Invalid Auth Key` etc.

**Comment by nbernardes** [comment]
@maennchen If the error can be changed it's a great start, since this way in production environments when the app crashes we know easily what was the cause of it (I already knew what could be the issue when the error `Fixer API Schema has changed.` but for new comers it can be a bit hard to understand 😜)

**Comment by maennchen** [comment]
@nunobernardes99 A PR for that would be very welcome.

Also: Please update to the latest major version.

`CurrencyConversion.Application` does no longer exist. Your application is supposed to do the supervision and you can also decide what happens if that fails.

**Comment by nbernardes** [comment]
@maennchen Oh you're right, we are not using the latest dependency version (we have forked your dependency to use the latest Money dep version) that's why we have that approach (my bad not pointing that out from the beginning). Should I do:
- PR to upgrade money dep
- PR to add the 2 new custom error messages?

Or do we have problems with increasing the money dep to the latest version?

**Comment by maennchen** [comment]
@nunobernardes99 I don't think that an update to `money` is necessary since this lib specifies `~ 1.2` and the latest `money` version is `1.8.0` which matches that requirement.

I believe you should probably update to the latest version and see if the same error persists. If the error is still in the latest version, open a PR for that.

**Comment by nbernardes** [comment]
Ok i've updated to the most recent version of the dependency and it seems that you already handle the errors:

When passing an invalid token:
``` elixir
[info] Application exited: Application.start(:normal, []) returned an error: shutdown: failed to start child:CurrencyConversion 
    ** (EXIT) shutdown: failed to start child: CurrencyConversion.UpdateWorker
        ** (EXIT) {:error, "Fixer API Error: You have not supplied a valid API Access Key. [Technical Support: support@apilayer.com]."}
** (Mix) Could not start application Application.start(:normal, []) returned an error: shutdown: failed to start child:CurrencyConversion
    ** (EXIT) shutdown: failed to start child: CurrencyConversion.UpdateWorker
        ** (EXIT) {:error, "Fixer API Error: You have not supplied a valid API Access Key. [Technical Support: support@apilayer.com]."}
```

So I think we're good, my problem was only that I did not updated to the latest version of the dependency.
Thanks a lot for the help!
