### ISSUE TITLE
Ability to avoid refresh on start?

### ISSUE THREAD

**Issue by strzibny** [jshmrtn/currency-conversion#8]
I would like to avoid automatic `refresh()` call on the update worker start: https://github.com/jshmrtn/currency-conversion/blob/master/lib/currency_conversion/update_worker.ex#L22

The use-case is that I wish to keep a given currency exchange same during the day. If the worker gets restarted it would change the exchange rates during the day. My work-flow would be to update the worker with a manual `refresh()` call (this is possible).

At last I would also need a function that can load the data I provide (rather then getting them from the service provider) and use them on start. Do you think we can support this in the library? I could make an attempt on adding this functionality.

If you think there is a better way to provide same-day rates I would welcome any suggestions.

**Comment by maennchen** [comment]
@strzibny Thanks for the suggestions.

> I would like to avoid automatic refresh() call on the update worker start

The initial refresh is needed so that any data is available at all. Otherwise there would be no data at all and the app could not do any conversions.

Was that the problem you were trying to solve with `At last I would also need a function that can load the data I provide`?

> worker with a manual refresh() call

We could for sure add a manual refresh, that would not be a problem. A PR for that is welcome.

* [x] Expsose `refresh/0` function
* [x] Allow `:none` / `:manual` /  `nil` (or any other naming if you have a better idea) for `refresh_interval` so that the refresh only happens manually.

**Comment by maennchen** [comment]
We could probably provide a `{M, f, [a]}` tuple as configuration to load the initial data instead of refresh when `refresh_interval` is disabled.

**Comment by strzibny** [comment]
Yes, pretty much.

As for `refresh_interval` would just setting `0` work to disable it? Or does it mean "refresh all the time"? 

As for the initial data, could a config for providing a function work? Like `seed_on_start: &MyApp.Currencies.import/0` (we would call this function in the worker to fetch the data instead of refresh).

**Comment by maennchen** [comment]
> As for refresh_interval would just setting 0 work to disable it? Or does it mean "refresh all the time"?

I would add a specific value to disable it. The number is just not clear on that. I think `:manual` would be a good value since it is descriptive.

> As for the initial data, could a config for providing a function work?

I think that should work fine,

We would need to provide the config option as both an mfa-tuple as well as a captured function. Config providers do not have the same flexibility as regular code does (especially when using releases).

**Comment by strzibny** [comment]
After looking at #12 I am working on getting the initial seed state from a provided configuration. I have one question though. I am not sure how to test it both for the function and refresh ("initial load called" test). If it's in the `test.exs` configuration as:

```
use Mix.Config

config :currency_conversion,
  source: CurrencyConversion.Source.Test,
  seed: {CurrencyConversion, :rates, []}
```
The `seed` is the provided function for seeding initial data when process starts/restarts.

The load test will then use this function and everything works. Except when I want to test the current behaviour when we do refresh on startup I cannot since the configuration specify the `seed` param.

Do you maybe have a good way on how to test both startup cases? Or should I just test one of those cases (e.g. keeping the current behaviour).

**Comment by maennchen** [comment]
@strzibny I have an alternate idea on how to build the whole thing. I would like to implement #9 including more tests and you can rebase on that. This should be a lot simpler I think.

**Comment by strzibny** [comment]
Sounds interesting and I am all ears. Are you getting closer on the implementation side of things? Right now I think I have to put something together fast so I can actually use it in the project I am working on. Any plans to at least move with #12? I can have my own fork until you will have the time to rearchitect with ETS. Then I can switch to your version.

**Comment by maennchen** [comment]
@strzibny I'm working on it right now, should be ready in an hour.

**Comment by maennchen** [comment]
@strzibny Done. You can rebase.

## Manual Refresh Interval:

Replace

```elixir
case refresh(opts) do
  :ok -> {:noreply, opts, refresh_interval}
  {:error, binary} -> {:stop, {:error, binary}}
end
```

with

```elixir
case {refresh(opts), refresh_interval} do
  {:ok, :manual} -> {:ok, opts}
  {:ok, _} -> {:ok, opts, refresh_interval}
  {{:error, binary}, _} -> {:stop, {:error, binary}}
end
```

and add a test with `refute_receive` `:load` as in this test:
https://github.com/jshmrtn/currency-conversion/blob/master/test/currency_conversion/update_worker_test.exs#L27

## Manual Refresh

Add this:

```elixir
@impl GenServer
def handle_call(:refresh, _from, opts) do
  refresh_interval = Keyword.get(opts, :refresh_interval, @default_refresh_interval)

  case {refresh(opts), refresh_interval} do
    {:ok, :manual} -> {:reply, :ok, opts}
    {:ok, _} -> {:reply, :ok, opts, refresh_interval}
    {{:error, binary}, :manual} -> {:reply, {:error, binary}, opts}
    {{:error, binary}, _} -> {:reply, {:error, binary}, opts, refresh_interval}
  end
end

@spec refresh_rates(worker_name :: atom()) :: :ok | {:error, string}
def refresh_rates(worker_name \\ __MODULE__) do
  GenServer.call(worker_name, :refresh)
end
```

Please add a test that the interval was added after a manual `refresh` when `refresh_interval` is number and also the opposite. (Inspiration: https://github.com/jshmrtn/currency-conversion/blob/master/test/currency_conversion/update_worker_test.exs#L27)

**Comment by maennchen** [comment]
@strzibny As soon as your PR's about `seed` & the `manual` interval are through, I'll release a new major version :)

**Comment by strzibny** [comment]
Ok perfect, thanks for the fast response, appreciate it, I will update the PR.

**Comment by maennchen** [comment]
Tracked further in #20
